# nfe/nfe_constants.py
#
# Todas as constantes específicas do domínio NF-e (DANFE).
# Isolado do core para não interferir nas regras de CT-e.

from typing import List, Set

# Namespace XML da NF-e
NFE_NAMESPACE: str = "http://www.portalfiscal.inf.br/nfe"

# ==================== Cabeçalhos da Planilha NF-e ====================
# Ordem exata conforme planilha de referência "Cópia de 2025 1.xlsx"
# 154 colunas no total.

NFE_HEADERS: List[str] = [
    # --- Identificação da Nota ---
    "NFe",
    "chv_nfe_Id",
    # --- Identificação ---
    "ide",
    "ide_cUF",
    "ide_cNF",
    "ide_natOp",
    "ide_mod",
    "ide_serie",
    "ide_nNF",
    "ide_dhEmi",
    "ide_tpNF",
    "ide_idDest",
    "ide_cMunFG",
    "ide_tpImp",
    "ide_tpEmis",
    "ide_cDV",
    "ide_tpAmb",
    "ide_finNFe",
    "ide_indFinal",
    "ide_indPres",
    "ide_indIntermed",
    "ide_procEmi",
    "ide_verProc",
    # --- Emitente ---
    "emit",
    "emit_CNPJ",
    "emit_xNome",
    "emit_xFant",
    "emit_enderEmit",
    "emit_enderEmit_xLgr",
    "emit_enderEmit_nro",
    "emit_enderEmit_xCpl",
    "emit_enderEmit_xBairro",
    "emit_enderEmit_cMun",
    "emit_enderEmit_xMun",
    "emit_enderEmit_UF",
    "emit_enderEmit_CEP",
    "emit_enderEmit_cPais",
    "emit_enderEmit_xPais",
    "emit_enderEmit_fone",
    "emit_IE",
    "emit_CRT",
    # --- Destinatário ---
    "dest",
    "dest_CNPJ",
    "dest_CPF",
    "dest_xNome",
    "dest_enderDest",
    "dest_enderDest_xLgr",
    "dest_enderDest_nro",
    "dest_enderDest_xCpl",
    "dest_enderDest_xBairro",
    "dest_enderDest_cMun",
    "dest_enderDest_xMun",
    "dest_enderDest_UF",
    "dest_enderDest_CEP",
    "dest_enderDest_cPais",
    "dest_enderDest_xPais",
    "dest_enderDest_fone",
    "dest_indIEDest",
    "dest_IE",
    # --- Totais ---
    "total",
    "total_ICMSTot",
    "total_ICMSTot_vBC",
    "total_ICMSTot_vICMS",
    "total_ICMSTot_vICMSDeson",
    "total_ICMSTot_vFCPUFDest",
    "total_ICMSTot_vICMSUFDest",
    "total_ICMSTot_vICMSUFRemet",
    "total_ICMSTot_vBCST",
    "total_ICMSTot_vST",
    "total_ICMSTot_vProd",
    "total_ICMSTot_vFrete",
    "total_ICMSTot_vSeg",
    "total_ICMSTot_vDesc",
    "total_ICMSTot_vII",
    "total_ICMSTot_vIPI",
    "total_ICMSTot_vPIS",
    "total_ICMSTot_vCOFINS",
    "total_ICMSTot_vOutro",
    "total_ICMSTot_vNF",
    "total_ICMSTot_vTotTrib",
    "total_ICMSTot_vFCP",
    "total_ICMSTot_vFCPST",
    "total_ICMSTot_vFCPSTRet",
    "total_ICMSTot_vIPIDevol",
    # --- Transporte ---
    "transp",
    "transp_modFrete",
    "transp_CNPJ",
    "transp_xNome",
    "transp_IE",
    "transp_xEnder",
    "transp_xMun",
    "transp_UF",
    # --- Cobrança ---
    "cobr",
    "cobr_fat",
    "cobr_fat_nFat",
    "cobr_fat_vOrig",
    "cobr_fat_vDesc",
    "cobr_fat_vLiq",
    # --- Informações Adicionais ---
    "infAdic",
    "infAdic_infAdFisco",
    "infAdic_infCpl",
    # --- Itens (repetidos por produto) ---
    "NFeITEM",
    "nItem_nItem",
    "prod",
    "prod_cProd",
    "prod_cEAN",
    "prod_xProd",
    "prod_NCM",
    "prod_CEST",
    "prod_CFOP",
    "prod_uCom",
    "prod_qCom",
    "prod_vUnCom",
    "prod_vProd",
    "prod_cEANTrib",
    "prod_uTrib",
    "prod_qTrib",
    "prod_vUnTrib",
    "prod_indTot",
    # --- Impostos do item ---
    "imposto",
    "imposto_vTotTrib",
    "imposto_ICMS",
    "imposto_ICMS_orig",
    "imposto_ICMS_CST",
    "imposto_ICMS_modBC",
    "imposto_ICMS_vBC",
    "imposto_ICMS_pICMS",
    "imposto_ICMS_vICMS",
    "imposto_IPI",
    "imposto_IPI_cEnq",
    "imposto_IPI_CST",
    "imposto_IPI_vBC",
    "imposto_IPI_pIPI",
    "imposto_IPI_vIPI",
    "imposto_PIS",
    "imposto_PIS_CST",
    "imposto_PIS_vBC",
    "imposto_PIS_pPIS",
    "imposto_PIS_vPIS",
    "imposto_COFINS",
    "imposto_COFINS_CST",
    "imposto_COFINS_vBC",
    "imposto_COFINS_pCOFINS",
    "imposto_COFINS_vCOFINS",
    "imposto_ICMSUFDest",
    "imposto_ICMSUFDest_vBCUFDest",
    "imposto_ICMSUFDest_pFCPUFDest",
    "imposto_ICMSUFDest_pICMSUFDest",
    "imposto_ICMSUFDest_pICMSInter",
    "imposto_ICMSUFDest_pICMSInterPart",
    "imposto_ICMSUFDest_vFCPUFDest",
    "imposto_ICMSUFDest_vICMSUFDest",
    "imposto_ICMSUFDest_vICMSUFRemet",
    "infAdProd",
]

# ==================== Colunas Separadoras (Fundo Cinza) ====================
# Identificadas pela cor FFA9A9A9 na planilha de referência.
NFE_GRAY_COLS: Set[str] = {
    "NFe",
    "ide",
    "emit",
    "emit_enderEmit",
    "dest",
    "dest_enderDest",
    "total",
    "total_ICMSTot",
    "transp",
    "cobr",
    "cobr_fat",
    "infAdic",
    "prod",
    "imposto",
    "imposto_ICMS",
    "imposto_IPI",
    "imposto_PIS",
    "imposto_COFINS",
    "imposto_ICMSUFDest",
}

# ==================== Colunas Numéricas / Monetárias ====================
# Receberão o formato de contabilidade #,##0.00 no Excel.
NFE_ACCOUNTING_COLS: Set[str] = {
    "total_ICMSTot_vBC",
    "total_ICMSTot_vICMS",
    "total_ICMSTot_vICMSDeson",
    "total_ICMSTot_vFCPUFDest",
    "total_ICMSTot_vICMSUFDest",
    "total_ICMSTot_vICMSUFRemet",
    "total_ICMSTot_vBCST",
    "total_ICMSTot_vST",
    "total_ICMSTot_vProd",
    "total_ICMSTot_vFrete",
    "total_ICMSTot_vSeg",
    "total_ICMSTot_vDesc",
    "total_ICMSTot_vII",
    "total_ICMSTot_vIPI",
    "total_ICMSTot_vPIS",
    "total_ICMSTot_vCOFINS",
    "total_ICMSTot_vOutro",
    "total_ICMSTot_vNF",
    "total_ICMSTot_vTotTrib",
    "total_ICMSTot_vFCP",
    "total_ICMSTot_vFCPST",
    "total_ICMSTot_vFCPSTRet",
    "total_ICMSTot_vIPIDevol",
    "cobr_fat_vOrig",
    "cobr_fat_vDesc",
    "cobr_fat_vLiq",
    "prod_qCom",
    "prod_vUnCom",
    "prod_vProd",
    "prod_qTrib",
    "prod_vUnTrib",
    "imposto_vTotTrib",
    "imposto_ICMS_vBC",
    "imposto_ICMS_pICMS",
    "imposto_ICMS_vICMS",
    "imposto_IPI_vBC",
    "imposto_IPI_pIPI",
    "imposto_IPI_vIPI",
    "imposto_PIS_vBC",
    "imposto_PIS_pPIS",
    "imposto_PIS_vPIS",
    "imposto_COFINS_vBC",
    "imposto_COFINS_pCOFINS",
    "imposto_COFINS_vCOFINS",
    "imposto_ICMSUFDest_vBCUFDest",
    "imposto_ICMSUFDest_pFCPUFDest",
    "imposto_ICMSUFDest_pICMSUFDest",
    "imposto_ICMSUFDest_pICMSInter",
    "imposto_ICMSUFDest_pICMSInterPart",
    "imposto_ICMSUFDest_vFCPUFDest",
    "imposto_ICMSUFDest_vICMSUFDest",
    "imposto_ICMSUFDest_vICMSUFRemet",
}
